import type { WorkflowEntry } from "./types.js";

export const residentWorkflows: readonly WorkflowEntry[] = [
  { id: "dashboard", title: "Training dashboard and progress", roles: ["student"], aliases: ["progress", "targets", "completion", "how am I doing"], href: "/", steps: ["Open Dashboard to see your progress, target requirements, and recent activity.", "Use the category details to see which verified entries count toward configured targets."], rules: ["Only verified records count as completed work.", "Targets depend on your department configuration."], blockers: ["If progress fails to load, retry or contact your department administrator; Arogya cannot see the failed request's historical state."], sources: ["artifacts/mockup-sandbox/src/components/layout/AppLayout.tsx", "artifacts/api-server/src/routes/student.ts"] },
  { id: "cases", title: "Case logs", roles: ["student"], aliases: ["case", "case log", "clinical case", "log a case", "cas"], availability: { key: "hideCaseLogs", enabledWhen: "not-true" }, href: "/cases", steps: ["Open Case Logs and choose the control to add a case.", "Complete the fields shown for your department and submit the form.", "Check the record status in the case list; a submitted record can remain pending until reviewed."], rules: ["Required fields and case categories can vary by department."], blockers: ["A hidden Case Logs feature is unavailable for your department.", "The current Save draft control does not persist a draft."], sources: ["artifacts/mockup-sandbox/src/App.tsx", "artifacts/mockup-sandbox/src/components/pages/CaseLogsPage.tsx", "artifacts/api-server/src/routes/student.ts"] },
  { id: "procedures", title: "Procedure logs", roles: ["student"], aliases: ["procedure", "procedure log", "competency", "supervision", "proceduer"], availability: { key: "hideProcedureLogs", enabledWhen: "not-true" }, href: "/procedures", steps: ["Open Procedure Logs and choose the control to add an entry.", "Select an available procedure and provide the supervision details requested.", "Submit the entry and check its status in the list."], rules: ["Procedure choices, competency options, and requirements are configured by department."], blockers: ["A hidden Procedure Logs feature is unavailable for your department.", "Some procedure options may be restricted by the department catalog."], sources: ["artifacts/mockup-sandbox/src/App.tsx", "artifacts/mockup-sandbox/src/components/pages/ProcedureLogsPage.tsx"] },
  { id: "academics", title: "Academic activities", roles: ["student"], aliases: ["academic", "journal club", "seminar", "presentation", "teaching"], href: "/academics", steps: ["Open Academic Activities and add the activity type available in your department.", "Complete the displayed date and activity details, then submit.", "Check the activity status in the list."], rules: ["Activity types and extra fields can depend on department settings."], blockers: ["If an activity type is not available, check the department's configured catalog."], sources: ["artifacts/mockup-sandbox/src/components/pages/AcademicLogsPage.tsx", "artifacts/api-server/src/routes/student.ts"] },
  { id: "clinical-work", title: "Clinical Work", roles: ["student"], aliases: ["clinical work", "clinical procedure", "category", "subtype"], availability: { key: "clinicalWorks", enabledWhen: true }, href: "/clinical-works", steps: ["Open Clinical Work and add an entry using the categories and fields displayed.", "Submit the entry and check its review status."], rules: ["Clinical Work is a separate configured workflow. Its categories and fields are department-specific."], blockers: ["This page is unavailable when Clinical Work is disabled."], sources: ["artifacts/mockup-sandbox/src/App.tsx", "artifacts/mockup-sandbox/src/components/pages/ClinicalWorksPage.tsx", "artifacts/api-server/src/routes/student.ts"] },
  { id: "conferences", title: "Conferences and CME", roles: ["student"], aliases: ["conference", "cme", "continuing medical education"], availability: { key: "attendedConferences", enabledWhen: true }, href: "/conferences", steps: ["Open Conferences and CME, add an attendance record, and provide the requested event details.", "Submit the record and check its status."], rules: ["The workflow is available only when enabled for your department."], blockers: ["A disabled conference feature has no active page."], sources: ["artifacts/mockup-sandbox/src/App.tsx", "artifacts/mockup-sandbox/src/components/pages/ConferencesPage.tsx"] },
  { id: "postings", title: "Postings and rotations", roles: ["student"], aliases: ["posting", "rotation", "schedule", "assignment", "assigned postings", "assigned posting", "rotation schedule", "posting schedule"], href: "/postings", steps: ["Open Postings and Rotations to view your assigned postings and schedule."], rules: ["Posting names and schedules are maintained for your department."], blockers: ["If your assignment is missing or appears incorrect, contact your HOD."], sources: ["artifacts/mockup-sandbox/src/components/layout/AppLayout.tsx", "artifacts/mockup-sandbox/src/App.tsx"] },
  { id: "leave", title: "Leave records", roles: ["student"], aliases: ["leave", "leave balance", "leave request", "attendance"], href: "/attendance", steps: ["Open Leave Records to review your leave balance, requests, and their status.", "Use the available request form to submit a leave request."], rules: ["Leave requests are subject to department review."], blockers: ["A pending request has not yet been approved."], sources: ["artifacts/mockup-sandbox/src/components/layout/AppLayout.tsx", "artifacts/api-server/src/routes/student.ts"] },
  { id: "assessments", title: "Assessments and appraisal records", roles: ["student"], aliases: ["assessment", "quarterly appraisal", "my appraisal", "scores", "feedback"], href: "/assessments", steps: ["Open Assessments to view assessment and quarterly appraisal records available to you."], rules: ["Residents can view their saved records; faculty and HODs create quarterly appraisals."], blockers: ["A record that has not been submitted by faculty or HOD will not appear as a saved appraisal."], sources: ["artifacts/mockup-sandbox/src/App.tsx", "artifacts/mockup-sandbox/src/components/pages/AssessmentsPage.tsx", "artifacts/api-server/src/routes/appraisals.ts"] },
  { id: "milestones", title: "Thesis and certifications", roles: ["student"], aliases: ["thesis", "publication", "certification", "milestone", "certificate"], availability: { key: "splitThesisAndCertifications", enabledWhen: "not-true" }, href: "/milestones", steps: ["Open Thesis & Certifications from the department navigation.", "Use the displayed form to add or update the relevant record and check its status."], rules: ["This combined page is used when the department has not split thesis/publication and certification workflows."], blockers: ["Departments with split workflows use separate pages."], sources: ["artifacts/mockup-sandbox/src/components/layout/AppLayout.tsx", "artifacts/mockup-sandbox/src/App.tsx"] },
  { id: "thesis", title: "Thesis and publications", roles: ["student"], aliases: ["thesis", "publication", "research"], availability: { key: "splitThesisAndCertifications", enabledWhen: true }, href: "/thesis", steps: ["Open the Thesis or Publications page shown in your department navigation.", "Use the displayed form to add or update the record and check its status."], rules: ["The label depends on the department's thesis/publication settings."], blockers: ["This separate page is unavailable when thesis and certifications are combined."], sources: ["artifacts/mockup-sandbox/src/components/layout/AppLayout.tsx", "artifacts/mockup-sandbox/src/App.tsx"] },
  { id: "certifications", title: "Certifications", roles: ["student"], aliases: ["certification", "certificate", "status of my certificate", "certificate status"], availability: { key: "splitThesisAndCertifications", enabledWhen: true }, unavailableWhen: [{ key: "publicationsOnly", enabledWhen: true }], href: "/certifications", steps: ["Open Certifications from the department navigation.", "Use the displayed form to add or update a certification and check its status."], rules: ["Certifications are shown separately when the department has split this workflow and has not configured a publications-only view."], blockers: ["This page is not shown in publications-only departments."], sources: ["artifacts/mockup-sandbox/src/components/layout/AppLayout.tsx", "artifacts/mockup-sandbox/src/App.tsx"] },
  { id: "awards", title: "Awards and achievements", roles: ["student"], aliases: ["award", "achievement", "prize"], availability: { key: "awards", enabledWhen: true }, href: "/awards", steps: ["Open Awards and Achievements and use the available form to record an award."], rules: ["This workflow is available only when enabled for your department."], blockers: ["If disabled, the page is unavailable."], sources: ["artifacts/mockup-sandbox/src/App.tsx", "artifacts/api-server/src/routes/student.ts"] },
  { id: "print-logbook", title: "Print your logbook", roles: ["student"], aliases: ["print", "download", "logbook pdf", "export"], href: "/print", steps: ["Choose Print from the application navigation to open the printable logbook.", "Use your browser's print or save-as-PDF option."], rules: ["The printable logbook reflects records available to your account."], blockers: [], sources: ["artifacts/mockup-sandbox/src/components/layout/AppLayout.tsx", "artifacts/mockup-sandbox/src/App.tsx"] },
  { id: "account", title: "Sign-in and account access", roles: ["student"], aliases: ["login", "password", "sign in", "account"], steps: ["Use the sign-in page and the account recovery options shown there.", "For account approval or department access, contact your HOD or administrator."], rules: ["Arogya cannot change account settings."], blockers: [], sources: ["artifacts/mockup-sandbox/src/App.tsx"] },
];
