INSERT INTO department_catalog (department_id, kind, name, value, parent_value) VALUES
(18, 'clinical_work_category', 'Conventional X-rays', 'Conventional X-rays', NULL),
(18, 'clinical_work_category', 'Special radiographic procedures', 'Special radiographic procedures', NULL),
(18, 'clinical_work_category', 'Ultrasound', 'Ultrasound', NULL),
(18, 'clinical_work_category', 'Doppler study', 'Doppler study', NULL),
(18, 'clinical_work_category', 'Mammogram', 'Mammogram', NULL),
(18, 'clinical_work_category', 'CT scan', 'CT scan', NULL),
(18, 'clinical_work_category', 'MRI scan', 'MRI scan', NULL),
(18, 'clinical_work_category', 'Guided procedures (CT / USG)', 'Guided procedures (CT / USG)', NULL),
(18, 'clinical_work_category', 'Interventional radiology', 'Interventional radiology', NULL),
(18, 'clinical_work_category', 'Emergencies', 'Emergencies', NULL),
(18, 'clinical_work_category', 'Nuclear Medicine', 'Nuclear Medicine', NULL),
(18, 'clinical_work_category', 'DRP (District Residency Programme)', 'DRP (District Residency Programme)', NULL),
(18, 'clinical_work_category', 'BLS and ACLS Training', 'BLS and ACLS Training', NULL),
(18, 'clinical_work_subtype', 'Abdomen', 'Abdomen', 'Ultrasound'),
(18, 'clinical_work_subtype', 'KUB (Kidney, Ureter, Bladder)', 'KUB (Kidney, Ureter, Bladder)', 'Ultrasound'),
(18, 'clinical_work_subtype', 'Obstetrics', 'Obstetrics', 'Ultrasound'),
(18, 'clinical_work_subtype', 'Musculoskeletal', 'Musculoskeletal', 'Ultrasound'),
(18, 'clinical_work_subtype', 'Neurosonogram', 'Neurosonogram', 'Ultrasound'),
(18, 'clinical_work_subtype', 'Cardiovascular', 'Cardiovascular', 'Ultrasound'),
(18, 'clinical_work_subtype', 'Small Parts', 'Small Parts', 'Ultrasound'),
(18, 'clinical_work_subtype', 'Peripheral Arterial Doppler', 'Peripheral Arterial Doppler', 'Doppler study'),
(18, 'clinical_work_subtype', 'Peripheral Venous Doppler', 'Peripheral Venous Doppler', 'Doppler study'),
(18, 'clinical_work_subtype', 'Renal Doppler', 'Renal Doppler', 'Doppler study'),
(18, 'clinical_work_subtype', 'Other Abdominal Doppler', 'Other Abdominal Doppler', 'Doppler study'),
(18, 'clinical_work_subtype', 'Neck Vessel Carotid Doppler', 'Neck Vessel Carotid Doppler', 'Doppler study'),
(18, 'clinical_work_subtype', 'Testicular Doppler', 'Testicular Doppler', 'Doppler study'),
(18, 'clinical_work_subtype', 'AV Fistula Mapping', 'AV Fistula Mapping', 'Doppler study'),
(18, 'clinical_work_subtype', 'Brain', 'Brain', 'CT scan'),
(18, 'clinical_work_subtype', 'Head Neck and PNS', 'Head Neck and PNS', 'CT scan'),
(18, 'clinical_work_subtype', 'Heart', 'Heart', 'CT scan'),
(18, 'clinical_work_subtype', 'Spine', 'Spine', 'CT scan'),
(18, 'clinical_work_subtype', 'Musculoskeletal', 'Musculoskeletal', 'CT scan'),
(18, 'clinical_work_subtype', 'Abdomen', 'Abdomen', 'CT scan'),
(18, 'clinical_work_subtype', 'Thorax', 'Thorax', 'CT scan'),
(18, 'clinical_work_subtype', 'CT Angiogram', 'CT Angiogram', 'CT scan'),
(18, 'clinical_work_subtype', 'CT Cisternography', 'CT Cisternography', 'CT scan'),
(18, 'clinical_work_subtype', 'Trauma Protocol', 'Trauma Protocol', 'CT scan'),
(18, 'clinical_work_subtype', 'Brain', 'Brain', 'MRI scan'),
(18, 'clinical_work_subtype', 'Spine', 'Spine', 'MRI scan'),
(18, 'clinical_work_subtype', 'Abdomen', 'Abdomen', 'MRI scan'),
(18, 'clinical_work_subtype', 'MRCP', 'MRCP', 'MRI scan'),
(18, 'clinical_work_subtype', 'MR Urogram', 'MR Urogram', 'MRI scan'),
(18, 'clinical_work_subtype', 'MSK', 'MSK', 'MRI scan'),
(18, 'clinical_work_subtype', 'Thorax', 'Thorax', 'MRI scan'),
(18, 'clinical_work_subtype', 'Heart', 'Heart', 'MRI scan'),
(18, 'clinical_work_subtype', 'MR Angio', 'MR Angio', 'MRI scan'),
(18, 'clinical_work_subtype', 'MR Fistulogram', 'MR Fistulogram', 'MRI scan'),
(18, 'clinical_work_subtype', 'MR Fetal and Placenta', 'MR Fetal and Placenta', 'MRI scan'),
(18, 'clinical_work_subtype', 'Intravenous Urography (IVU)', 'Intravenous Urography (IVU)', 'Special radiographic procedures'),
(18, 'clinical_work_subtype', 'Micturating Cystourethrography (MCU)', 'Micturating Cystourethrography (MCU)', 'Special radiographic procedures'),
(18, 'clinical_work_subtype', 'Retrograde Urethrography (RGU)', 'Retrograde Urethrography (RGU)', 'Special radiographic procedures'),
(18, 'clinical_work_subtype', 'Hysterosalpingography (HSG)', 'Hysterosalpingography (HSG)', 'Special radiographic procedures'),
(18, 'clinical_work_subtype', 'Gastrointestinal Tract (GIT) Barium Studies', 'Gastrointestinal Tract (GIT) Barium Studies', 'Special radiographic procedures'),
(18, 'clinical_work_subtype', 'Dacryocystography (DCG)', 'Dacryocystography (DCG)', 'Special radiographic procedures'),
(18, 'clinical_work_subtype', 'Sinogram & Fistulogram', 'Sinogram & Fistulogram', 'Special radiographic procedures'),
(18, 'clinical_work_subtype', 'CT Guided Biopsy', 'CT Guided Biopsy', 'Guided procedures (CT / USG)'),
(18, 'clinical_work_subtype', 'USG Guided Biopsy', 'USG Guided Biopsy', 'Guided procedures (CT / USG)'),
(18, 'clinical_work_subtype', 'USG Guided FNAC', 'USG Guided FNAC', 'Guided procedures (CT / USG)'),
(18, 'clinical_work_subtype', 'USG Guided Ascitic Fluid and Pleural Tap', 'USG Guided Ascitic Fluid and Pleural Tap', 'Guided procedures (CT / USG)'),
(18, 'clinical_work_subtype', 'USG Guided Drainage Tube Placement', 'USG Guided Drainage Tube Placement', 'Guided procedures (CT / USG)'),
(18, 'clinical_work_subtype', 'Guided Abscess Drainage', 'Guided Abscess Drainage', 'Guided procedures (CT / USG)'),
(18, 'clinical_work_category', 'Emergencies', 'Emergencies', NULL),
(18, 'clinical_work_subtype', 'Abdominal', 'Abdominal', 'Emergencies'),
(18, 'clinical_work_subtype', 'Obstetric', 'Obstetric', 'Emergencies'),
(18, 'clinical_work_subtype', 'Cardiovascular', 'Cardiovascular', 'Emergencies'),
(18, 'clinical_work_subtype', 'Thoracic', 'Thoracic', 'Emergencies'),
(18, 'clinical_work_subtype', 'Head and Neck', 'Head and Neck', 'Emergencies'),
(18, 'clinical_work_subtype', 'MSK', 'MSK', 'Emergencies'),
(18, 'clinical_work_subtype', 'Trauma', 'Trauma', 'Emergencies'),
(18, 'clinical_work_subtype', 'Others', 'Others', 'Emergencies'),
(19, 'clinical_work_category', 'Conventional X-rays', 'Conventional X-rays', NULL),
(19, 'clinical_work_category', 'Special radiographic procedures', 'Special radiographic procedures', NULL),
(19, 'clinical_work_category', 'Ultrasound', 'Ultrasound', NULL),
(19, 'clinical_work_category', 'Doppler study', 'Doppler study', NULL),
(19, 'clinical_work_category', 'Mammogram', 'Mammogram', NULL),
(19, 'clinical_work_category', 'CT scan', 'CT scan', NULL),
(19, 'clinical_work_category', 'MRI scan', 'MRI scan', NULL),
(19, 'clinical_work_category', 'Guided procedures (CT / USG)', 'Guided procedures (CT / USG)', NULL),
(19, 'clinical_work_category', 'Interventional radiology', 'Interventional radiology', NULL),
(19, 'clinical_work_category', 'Emergencies', 'Emergencies', NULL),
(19, 'clinical_work_category', 'Nuclear Medicine', 'Nuclear Medicine', NULL),
(19, 'clinical_work_category', 'DRP (District Residency Programme)', 'DRP (District Residency Programme)', NULL),
(19, 'clinical_work_category', 'BLS and ACLS Training', 'BLS and ACLS Training', NULL),
(19, 'clinical_work_subtype', 'Abdomen', 'Abdomen', 'Ultrasound'),
(19, 'clinical_work_subtype', 'KUB (Kidney, Ureter, Bladder)', 'KUB (Kidney, Ureter, Bladder)', 'Ultrasound'),
(19, 'clinical_work_subtype', 'Obstetrics', 'Obstetrics', 'Ultrasound'),
(19, 'clinical_work_subtype', 'Musculoskeletal', 'Musculoskeletal', 'Ultrasound'),
(19, 'clinical_work_subtype', 'Neurosonogram', 'Neurosonogram', 'Ultrasound'),
(19, 'clinical_work_subtype', 'Cardiovascular', 'Cardiovascular', 'Ultrasound'),
(19, 'clinical_work_subtype', 'Small Parts', 'Small Parts', 'Ultrasound'),
(19, 'clinical_work_subtype', 'Peripheral Arterial Doppler', 'Peripheral Arterial Doppler', 'Doppler study'),
(19, 'clinical_work_subtype', 'Peripheral Venous Doppler', 'Peripheral Venous Doppler', 'Doppler study'),
(19, 'clinical_work_subtype', 'Renal Doppler', 'Renal Doppler', 'Doppler study'),
(19, 'clinical_work_subtype', 'Other Abdominal Doppler', 'Other Abdominal Doppler', 'Doppler study'),
(19, 'clinical_work_subtype', 'Neck Vessel Carotid Doppler', 'Neck Vessel Carotid Doppler', 'Doppler study'),
(19, 'clinical_work_subtype', 'Testicular Doppler', 'Testicular Doppler', 'Doppler study'),
(19, 'clinical_work_subtype', 'AV Fistula Mapping', 'AV Fistula Mapping', 'Doppler study'),
(19, 'clinical_work_subtype', 'Brain', 'Brain', 'CT scan'),
(19, 'clinical_work_subtype', 'Head Neck and PNS', 'Head Neck and PNS', 'CT scan'),
(19, 'clinical_work_subtype', 'Heart', 'Heart', 'CT scan'),
(19, 'clinical_work_subtype', 'Spine', 'Spine', 'CT scan'),
(19, 'clinical_work_subtype', 'Musculoskeletal', 'Musculoskeletal', 'CT scan'),
(19, 'clinical_work_subtype', 'Abdomen', 'Abdomen', 'CT scan'),
(19, 'clinical_work_subtype', 'Thorax', 'Thorax', 'CT scan'),
(19, 'clinical_work_subtype', 'CT Angiogram', 'CT Angiogram', 'CT scan'),
(19, 'clinical_work_subtype', 'CT Cisternography', 'CT Cisternography', 'CT scan'),
(19, 'clinical_work_subtype', 'Trauma Protocol', 'Trauma Protocol', 'CT scan'),
(19, 'clinical_work_subtype', 'Brain', 'Brain', 'MRI scan'),
(19, 'clinical_work_subtype', 'Spine', 'Spine', 'MRI scan'),
(19, 'clinical_work_subtype', 'Abdomen', 'Abdomen', 'MRI scan'),
(19, 'clinical_work_subtype', 'MRCP', 'MRCP', 'MRI scan'),
(19, 'clinical_work_subtype', 'MR Urogram', 'MR Urogram', 'MRI scan'),
(19, 'clinical_work_subtype', 'MSK', 'MSK', 'MRI scan'),
(19, 'clinical_work_subtype', 'Thorax', 'Thorax', 'MRI scan'),
(19, 'clinical_work_subtype', 'Heart', 'Heart', 'MRI scan'),
(19, 'clinical_work_subtype', 'MR Angio', 'MR Angio', 'MRI scan'),
(19, 'clinical_work_subtype', 'MR Fistulogram', 'MR Fistulogram', 'MRI scan'),
(19, 'clinical_work_subtype', 'MR Fetal and Placenta', 'MR Fetal and Placenta', 'MRI scan'),
(19, 'clinical_work_subtype', 'Intravenous Urography (IVU)', 'Intravenous Urography (IVU)', 'Special radiographic procedures'),
(19, 'clinical_work_subtype', 'Micturating Cystourethrography (MCU)', 'Micturating Cystourethrography (MCU)', 'Special radiographic procedures'),
(19, 'clinical_work_subtype', 'Retrograde Urethrography (RGU)', 'Retrograde Urethrography (RGU)', 'Special radiographic procedures'),
(19, 'clinical_work_subtype', 'Hysterosalpingography (HSG)', 'Hysterosalpingography (HSG)', 'Special radiographic procedures'),
(19, 'clinical_work_subtype', 'Gastrointestinal Tract (GIT) Barium Studies', 'Gastrointestinal Tract (GIT) Barium Studies', 'Special radiographic procedures'),
(19, 'clinical_work_subtype', 'Dacryocystography (DCG)', 'Dacryocystography (DCG)', 'Special radiographic procedures'),
(19, 'clinical_work_subtype', 'Sinogram & Fistulogram', 'Sinogram & Fistulogram', 'Special radiographic procedures'),
(19, 'clinical_work_subtype', 'CT Guided Biopsy', 'CT Guided Biopsy', 'Guided procedures (CT / USG)'),
(19, 'clinical_work_subtype', 'USG Guided Biopsy', 'USG Guided Biopsy', 'Guided procedures (CT / USG)'),
(19, 'clinical_work_subtype', 'USG Guided FNAC', 'USG Guided FNAC', 'Guided procedures (CT / USG)'),
(19, 'clinical_work_subtype', 'USG Guided Ascitic Fluid and Pleural Tap', 'USG Guided Ascitic Fluid and Pleural Tap', 'Guided procedures (CT / USG)'),
(19, 'clinical_work_subtype', 'USG Guided Drainage Tube Placement', 'USG Guided Drainage Tube Placement', 'Guided procedures (CT / USG)'),
(19, 'clinical_work_subtype', 'Guided Abscess Drainage', 'Guided Abscess Drainage', 'Guided procedures (CT / USG)'),
(19, 'clinical_work_category', 'Emergencies', 'Emergencies', NULL),
(19, 'clinical_work_subtype', 'Abdominal', 'Abdominal', 'Emergencies'),
(19, 'clinical_work_subtype', 'Obstetric', 'Obstetric', 'Emergencies'),
(19, 'clinical_work_subtype', 'Cardiovascular', 'Cardiovascular', 'Emergencies'),
(19, 'clinical_work_subtype', 'Thoracic', 'Thoracic', 'Emergencies'),
(19, 'clinical_work_subtype', 'Head and Neck', 'Head and Neck', 'Emergencies'),
(19, 'clinical_work_subtype', 'MSK', 'MSK', 'Emergencies'),
(19, 'clinical_work_subtype', 'Trauma', 'Trauma', 'Emergencies'),
(19, 'clinical_work_subtype', 'Others', 'Others', 'Emergencies')
ON CONFLICT (department_id, kind, value) DO NOTHING;